version: "3"

services:
  producer:
    build: ./producer
    container_name: producer
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3000
    volumes:
      - ./producer:/home/node/producer
    depends_on: 
      - rabbitmq
    command: >
      bash -c "cd /home/node/producer && npm install && npm run start"

  consumer:
    build: ./consumer
    container_name: consumer
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./consumer:/home/node/consumer
    depends_on: 
      - rabbitmq
    command: >
      bash -c "cd /home/node/consumer && npm install && npm run start"

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080